version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root  # Remplace par ton mot de passe root
      MYSQL_DATABASE: database         # Remplace par le nom de ta base de données
      MYSQL_USER: user                    # Remplace par ton nom d'utilisateur
      MYSQL_PASSWORD: password       # Remplace par ton mot de passe
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8087:80"  # Accès à phpMyAdmin depuis http://localhost:8087
    depends_on:
      - mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
