version: '3'
services:
  django_app:
    build:
      context: ./auth_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./auth_app:/app
      - /home/yves/iadev-python/c13/best_model.keras:/app/best_model.keras
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8083:8081"  # Port de Mongo Express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db  # Nom du service MongoDB
    depends_on:
      - mongo_db

volumes:
  mongo_data:
