FROM python:3.8-slim

WORKDIR /app

# Installer les dépendances
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copier le code source
COPY . /app

# Exposer le port
EXPOSE 8000

# Lancer l'application Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
