name: CI/CD Pipeline

on:
  push:
    branches:
      - front  # Trigger on pushes to the "front" branch
  pull_request:
    branches:
      - front  # Trigger on pull requests to the "front" branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Retrieve the source code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the version of Python to use

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Use a relative path to requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Replace "tests" with the directory containing your tests

      - name: Build and deploy
        run: |
          # Add your build and deployment commands here, for example:
          # python -m your_application_module
          echo "Déploiement de l'application"  # Placeholder for deployment commands
