name: CI/CD Pipeline

on:
  push:
    branches:
      - front  # ou toute autre branche que tu veux surveiller
  pull_request:
    branches:
      - front

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Spécifie la version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover  # Exécute les tests
      
      - name: Deploy
        run: |
          echo "Déploiement de l'application"  # Ajoute ici les commandes de déploiement
