name: CI/CD Pipeline

on:
  push:
    branches:
      - front
  pull_request:
    branches:
      - front

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assure-toi que ce chemin est correct

      - name: Run tests
        run: |
          python -m unittest discover
