name: CI

on:
  push:
    branches:
      - front  # Modifiez cela selon votre branche
  pull_request:
    branches:
      - front  # Modifiez cela selon votre branche

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Mise à jour vers v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Mise à jour vers v4
      with:
        python-version: '3.10'  # Choisissez la version de Python que vous utilisez

    # Cette section installera les dépendances depuis le chemin spécifié
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt  # Assurez-vous du bon chemin vers le requirements.txt

    - name: Run tests
      run: |
        python manage.py test  # Commande pour exécuter vos tests

