name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.15'  # Remplacez par la version de Python que vous utilisez

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Check if requirements.txt exists
        run: |
          if [ ! -f /home/yves/iadev-python/c13/requirements.txt ]; then
            echo "requirements.txt not found!"
            exit 1
          fi

      - name: Install dependencies
        run: |
          pip install -r /home/yves/iadev-python/c13/requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s /home/yves/iadev-python/c13/test
