name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Configurer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Spécifiez la version de Python que vous utilisez

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assurez-vous d'avoir un fichier requirements.txt

      - name: Exécuter les tests
        run: |
          python -m unittest discover  # Exécute tous les tests dans le répertoire courant
